--------------------------------------------------------
--  Fichier créé - vendredi-mai-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."DOCUMENT" 
   (	"IDDOC" NUMBER, 
	"AUTEUR" VARCHAR2(20 BYTE), 
	"TITRE" VARCHAR2(20 BYTE), 
	"DATTE" VARCHAR2(20 BYTE), 
	"TEXTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOSSIER
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."DOSSIER" 
   (	"IDDOS" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATTE" VARCHAR2(20 BYTE), 
	"CONTENU" VARCHAR2(20 BYTE), 
	"PROP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKINGS
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."PARKINGS" 
   (	"TAILLEPARKING" NUMBER(*,0), 
	"NBVEHICULESPARKING" NUMBER(*,0), 
	"PLACESVIDESPARKING" NUMBER(*,0), 
	"IDPARKING" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRISONNIERS
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."PRISONNIERS" 
   (	"IDPRISONNIER" VARCHAR2(30 BYTE), 
	"NOMPRISONNIER" VARCHAR2(30 BYTE), 
	"PRENOMPRISONNIER" VARCHAR2(30 BYTE), 
	"CRIMEPRISONNIER" VARCHAR2(30 BYTE), 
	"CINPRISONNIER" VARCHAR2(30 BYTE), 
	"DATE_NAISSANCE_PRISONNIER" DATE, 
	"NUMCELLULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILS
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."PROFILS" 
   (	"IDPROFIL" VARCHAR2(50 BYTE), 
	"FONCTION" VARCHAR2(50 BYTE), 
	"GRADE" VARCHAR2(50 BYTE), 
	"DEPARTEMENT" VARCHAR2(50 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."RECLAMATION" 
   (	"ID_RECLAMATION" NUMBER, 
	"ID_CITOYEN" NUMBER, 
	"TYPE_RECLAMATION" VARCHAR2(20 BYTE), 
	"DATE_RECLAMATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULES
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."VEHICULES" 
   (	"MATRICULEVEHICULE" VARCHAR2(30 BYTE), 
	"MARQUEVEHICULE" VARCHAR2(30 BYTE), 
	"TYPEVEHICULE" VARCHAR2(30 BYTE), 
	"COULEURVEHICULE" VARCHAR2(30 BYTE), 
	"DATE_ACQUISITION" DATE, 
	"IDPARKING" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITOYEN
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."CITOYEN" 
   (	"CIN" NUMBER(*,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"NUM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CELLULES
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."CELLULES" 
   (	"IDCELLULE" VARCHAR2(50 BYTE), 
	"NUMCELLULE" NUMBER, 
	"CAPACITECELLULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AGENTS
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."AGENTS" 
   (	"IDAGENT" VARCHAR2(50 BYTE), 
	"NOMAGENT" VARCHAR2(50 BYTE), 
	"PRENOMAGENT" VARCHAR2(50 BYTE), 
	"AGEAGENT" NUMBER, 
	"CINAGENT" VARCHAR2(50 BYTE), 
	"PASSWORDAGENT" VARCHAR2(50 BYTE), 
	"DATE_NAISSANCE_AGENT" DATE, 
	"DROITACCESAGENT" VARCHAR2(50 BYTE) DEFAULT 'Standard'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YOUSSEF.DOCUMENT
SET DEFINE OFF;
Insert into YOUSSEF.DOCUMENT (IDDOC,AUTEUR,TITRE,DATTE,TEXTE) values ('456','hgd','gdf','01 janvier','tgdfsdehrtdgfdgd');
REM INSERTING into YOUSSEF.DOSSIER
SET DEFINE OFF;
Insert into YOUSSEF.DOSSIER (IDDOS,NOM,DATTE,CONTENU,PROP) values ('5424','hgf','jhfghf','fhgfgghfs','tyhtgd');
Insert into YOUSSEF.DOSSIER (IDDOS,NOM,DATTE,CONTENU,PROP) values ('65456','hgf','jhfghf','fhgfgghfs','tyhtgd');
Insert into YOUSSEF.DOSSIER (IDDOS,NOM,DATTE,CONTENU,PROP) values ('65456','ahmed','janivier','centenuu','proooo');
Insert into YOUSSEF.DOSSIER (IDDOS,NOM,DATTE,CONTENU,PROP) values ('446','yuu','ityut','zzzz','aaaa');
Insert into YOUSSEF.DOSSIER (IDDOS,NOM,DATTE,CONTENU,PROP) values ('44','zzzz','mmmm','yyyyy','bbbb');
REM INSERTING into YOUSSEF.PARKINGS
SET DEFINE OFF;
Insert into YOUSSEF.PARKINGS (TAILLEPARKING,NBVEHICULESPARKING,PLACESVIDESPARKING,IDPARKING) values ('6','66','59','45');
Insert into YOUSSEF.PARKINGS (TAILLEPARKING,NBVEHICULESPARKING,PLACESVIDESPARKING,IDPARKING) values ('46','6','57','88');
REM INSERTING into YOUSSEF.PRISONNIERS
SET DEFINE OFF;
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('Tr4Y93jEjRPWDh6lOVbr8g==','sabri','ali','Braquage','158526',to_date('01/01/96','DD/MM/RR'),'22222');
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('ULKrKbHhkbz7UNu5RusEMw==','hmed','salah','meurtre','4188465',to_date('01/01/50','DD/MM/RR'),'554');
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('Gq3HhFw7SxyFCwKBTNt2TQ==','hmed','amine','meurtre','4858461',to_date('01/01/70','DD/MM/RR'),'55');
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('7iUTbuIEqkQ2K1REv2VW+A==','sofiene','test','Meurtre','5856529',to_date('01/01/86','DD/MM/RR'),'2');
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('TAu8naNuJ9rdyCM0E5dh8w==','tegrt','tr','trtr','45896123',to_date('01/01/00','DD/MM/RR'),null);
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('vv8/y6VvKWd8XVK4Q982Xg==','test1','test2','test3','548',to_date('01/01/88','DD/MM/RR'),'4');
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('v1WlgBtR1AMdW21Gjg8L7A==','a2','a3','a4','a1',to_date('01/01/00','DD/MM/RR'),null);
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('Sgxs+R0I72MSp0qZuJ+CZg==','testtt','sddq','dfhdgs','52314689',to_date('01/01/00','DD/MM/RR'),null);
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('ADt3JV5d8PctMOA/e5iv2Q==','alin','sddq','dfhdgs','14569823',to_date('01/01/00','DD/MM/RR'),null);
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('24YJ4vpiKvdh/FwEg6CbGA==','amin5','amin5','amin6','amin4',to_date('01/01/00','DD/MM/RR'),null);
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('wpRuI2eN2mkQebzbC6mgCQ==','fsdfd','gfsfd','ztsdr','12453678',to_date('01/01/00','DD/MM/RR'),null);
Insert into YOUSSEF.PRISONNIERS (IDPRISONNIER,NOMPRISONNIER,PRENOMPRISONNIER,CRIMEPRISONNIER,CINPRISONNIER,DATE_NAISSANCE_PRISONNIER,NUMCELLULE) values ('tmju9KzctJq4c29H4K/DwQ==','tyjhdf','rtytrye','yuutiy','12345678',to_date('02/01/00','DD/MM/RR'),null);
REM INSERTING into YOUSSEF.PROFILS
SET DEFINE OFF;
Insert into YOUSSEF.PROFILS (IDPROFIL,FONCTION,GRADE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE) values ('xrk5Aefv8TNAP/YqSGEBCg==','zzzz','zzzzzzzzz','zzzzzzzzzz',to_date('05/01/00','DD/MM/RR'),'11');
Insert into YOUSSEF.PROFILS (IDPROFIL,FONCTION,GRADE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE) values ('1GqLdRDUdzPOQbgOu4zR4Q==','ghh','jhj','fffffffffffffff',to_date('03/01/00','DD/MM/RR'),'55');
Insert into YOUSSEF.PROFILS (IDPROFIL,FONCTION,GRADE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE) values ('uDbhuqSOlkSOkJnKNcpmHA==','rrrrrrrr','eee','hhhh',to_date('04/01/00','DD/MM/RR'),'22');
REM INSERTING into YOUSSEF.RECLAMATION
SET DEFINE OFF;
Insert into YOUSSEF.RECLAMATION (ID_RECLAMATION,ID_CITOYEN,TYPE_RECLAMATION,DATE_RECLAMATION) values ('546','88','accident','01/01/00');
Insert into YOUSSEF.RECLAMATION (ID_RECLAMATION,ID_CITOYEN,TYPE_RECLAMATION,DATE_RECLAMATION) values ('5865','556','meurte','03/01/00');
REM INSERTING into YOUSSEF.VEHICULES
SET DEFINE OFF;
Insert into YOUSSEF.VEHICULES (MATRICULEVEHICULE,MARQUEVEHICULE,TYPEVEHICULE,COULEURVEHICULE,DATE_ACQUISITION,IDPARKING) values ('8577','ter','etrtry','noire',to_date('03/01/00','DD/MM/RR'),'45');
REM INSERTING into YOUSSEF.CITOYEN
SET DEFINE OFF;
Insert into YOUSSEF.CITOYEN (CIN,NOM,PRENOM,ADRESSE,NUM) values ('12454355','mahditouu','sebaiitooo','dhabout l guerda','6969696');
Insert into YOUSSEF.CITOYEN (CIN,NOM,PRENOM,ADRESSE,NUM) values ('5544','lllllllll','oooooooo','aaaa','55');
REM INSERTING into YOUSSEF.CELLULES
SET DEFINE OFF;
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('yB5yjZ1ML2NvBn+JzBSGLA==','1000','1');
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('qrMjiSK8wlpvYG61Jf/cVg==','2','444');
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('cNyF3u7XiW0c0rEO1Ey3xw==','554','54645');
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('VMtIfVgRCwhp5+Q1F1662A==','22222','444');
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('X5P5g1JN7z3KRkRp0s+fPg==','55','555');
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('NBc8s48H+J3b68KskSgwPw==','15','15');
Insert into YOUSSEF.CELLULES (IDCELLULE,NUMCELLULE,CAPACITECELLULE) values ('yfD4lfuYq5FZ9R/QKX4jbQ==','4','4');
REM INSERTING into YOUSSEF.AGENTS
SET DEFINE OFF;
Insert into YOUSSEF.AGENTS (IDAGENT,NOMAGENT,PRENOMAGENT,AGEAGENT,CINAGENT,PASSWORDAGENT,DATE_NAISSANCE_AGENT,DROITACCESAGENT) values ('ingmwCc+EcjC1puCZRYJmg==','Mike','Steve','46','11445566','1234',to_date('01/01/00','DD/MM/RR'),'Standard');
--------------------------------------------------------
--  DDL for Index SYS_C007296
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."SYS_C007296" ON "YOUSSEF"."PARKINGS" ("IDPARKING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007086
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."SYS_C007086" ON "YOUSSEF"."PRISONNIERS" ("IDPRISONNIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007288
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."SYS_C007288" ON "YOUSSEF"."PROFILS" ("IDPROFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007298
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."SYS_C007298" ON "YOUSSEF"."VEHICULES" ("MATRICULEVEHICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007135
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."SYS_C007135" ON "YOUSSEF"."CELLULES" ("NUMCELLULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007287
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."SYS_C007287" ON "YOUSSEF"."AGENTS" ("IDAGENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PARKINGS
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."PARKINGS" ADD PRIMARY KEY ("IDPARKING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRISONNIERS
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."PRISONNIERS" ADD PRIMARY KEY ("IDPRISONNIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILS
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."PROFILS" ADD PRIMARY KEY ("IDPROFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."VEHICULES" ADD PRIMARY KEY ("MATRICULEVEHICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CELLULES
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."CELLULES" ADD PRIMARY KEY ("NUMCELLULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENTS
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."AGENTS" ADD PRIMARY KEY ("IDAGENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRISONNIERS
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."PRISONNIERS" ADD FOREIGN KEY ("NUMCELLULE")
	  REFERENCES "YOUSSEF"."CELLULES" ("NUMCELLULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."VEHICULES" ADD FOREIGN KEY ("IDPARKING")
	  REFERENCES "YOUSSEF"."PARKINGS" ("IDPARKING") ENABLE;
